# Generated by Django 5.0.7 on 2024-08-24 03:40

import django.db.models.deletion
import papers.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=255)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('cover_page', models.ImageField(blank=True, null=True, upload_to=papers.models.get_paper_cover_path)),
                ('year_published', models.CharField(blank=True, max_length=255, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=papers.models.get_paper_file_path)),
                ('is_open_access', models.BooleanField(blank=True, null=True)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('citations', models.IntegerField(blank=True, null=True)),
                ('references', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='papers.category')),
            ],
        ),
    ]
