# Generated by Django 5.0.7 on 2024-08-24 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ManyToManyField(blank=True, to='papers.category'),
        ),
        migrations.AddField(
            model_name='papers',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='papers.subcategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='type',
            field=models.ManyToManyField(blank=True, to='papers.type'),
        ),
        migrations.AddField(
            model_name='papers',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='papers.type'),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ManyToManyField(blank=True, to='papers.type'),
        ),
    ]
