# Generated by Django 5.0.7 on 2024-08-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_category_id_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='papers',
            name='resource_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
