# Generated by Django 5.0.7 on 2024-08-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_papers_price_papers_resource_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
