# Generated by Django 5.0.7 on 2024-08-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_alter_category_name_alter_papers_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
