# Generated by Django 5.0.7 on 2024-08-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_papers_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='file_url',
        ),
        migrations.AddField(
            model_name='papers',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/papers/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/papers/<django.db.models.fields.CharField>/cover'),
        ),
    ]
