# Generated by Django 5.0.7 on 2024-08-12 04:50

import papers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_remove_papers_file_url_papers_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='cover_page',
            field=models.ImageField(blank=True, null=True, upload_to=papers.models.get_paper_cover_path),
        ),
        migrations.AlterField(
            model_name='papers',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=papers.models.get_paper_file_path),
        ),
    ]
