# Generated by Django 5.0.7 on 2024-08-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0008_alter_papers_cover_page_alter_papers_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='year_published',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
