# Generated by Django 5.0.7 on 2024-08-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0009_alter_papers_year_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='new_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
