# Generated by Django 5.0.7 on 2024-09-05 07:11

import papers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0011_remove_papers_new_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='cover_page',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=papers.models.get_paper_cover_path),
        ),
        migrations.AlterField(
            model_name='papers',
            name='name',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
