# Generated by Django 5.0.7 on 2024-09-05 07:30

import papers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0012_alter_papers_cover_page_alter_papers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='cover_page',
            field=models.ImageField(blank=True, max_length=450, null=True, upload_to=papers.models.get_paper_cover_path),
        ),
    ]
