# Generated by Django 5.0.7 on 2024-08-22 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_vendor',
            new_name='is_publisher',
        ),
    ]
